server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      uri: mongodb+srv://vallegrandeomar:oFnm1G368PeimZNj@cluster0.srr0s.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: nosql

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG
    pe.edu.vallegrande: DEBUG
    org.springframework.web: DEBUG
    com.mongodb: DEBUG
